### ISSUE TITLE
How exactly is GPT-4 supported? 

### ISSUE THREAD

**Issue by kaklik** [yaroslavyaroslav/OpenAI-sublime-text#23]
I have issue with change of default models  deprecated     

    "edit_model": "code-davinci-edit-001",
    "model": "text-davinci-003",
    "chat_model": "gpt-3.5-turbo", 

To [suggested replacement](https://platform.openai.com/docs/deprecations/edit-models-endpoint)

	"edit_model": "gpt-4",
	"model": "gpt-4",
	"chat_model": "gpt-4"

Unfortunately I then getting the following message in case I try to call GPT-4 to edit the code: 

![image](https://github.com/yaroslavyaroslav/OpenAI-sublime-text/assets/1194177/d611f36b-a260-4c49-b6b9-f752e1b126bc)

**Comment by yaroslavyaroslav** [comment]
Hi, thank for your issues. 

Unfortunately gpt-4 supported only for the completion mode as for now. 

So the error that you're reffering to is pretty much unavoidable for both `edit` and `insert` modes. 

Later on I'll update the plugin to make it support the all brand new model for those modes as well.

**Comment by yaroslavyaroslav** [comment]
FYI: Recently I've got newsletter from OpenAI about new instruct model release. It's not GPT-4 yet, but at least it's GPT-3.5. There's two models reveals available for me in response to the related API request: (1) `gpt-3.5-turbo-instruct-0914` and (2) `gpt-3.5-turbo-instruct`, I believe there's no difference between as for now. These models are capable only with `v1/complete` gateway, which is corresponds with `OpenAI: Complete` and `OpenAI: Insert` actions and NOT corresponds with `OpenAI: Edit` (which is your issue about).

Another major point regarding that issue is that I've no plans to update both `model` and `edit_model` behaviour in any way because both of gateways behind them are deprecated and would be abandoned at the very beginning of the 2024 regarding to a OpenAI release. Though this features would be provided by chat-completion models soon before this abandon appears.
