### ISSUE TITLE
Missing placeholder in insert mode, API request still sent

### ISSUE THREAD

**Issue by issuj** [yaroslavyaroslav/OpenAI-sublime-text#58]
Steps:
1. Select code without the placeholder
2. OpenAI: Chat Model Select
3. Choose model with insert mode
4. Get the error "There is no placeholder [blaa] within the selected text. There should be exactly one."

Expected behavior:
No request to LLM inference API is made.

Actual behavior:
A request to LLM inference API is started. Additionally, it can not be aborted with stop_openai_execution keybind.

Plugin version: 4.1.0

Noticed because my local rig has coil whine. :hear_no_evil:

**Comment by yaroslavyaroslav** [comment]
Thanks, I'm near to the end to accomplishing grand refactoring goal, so there's a significant chance that this bit would be fixed quite soon.

**Comment by yaroslavyaroslav** [comment]
Yeah, important thing, due to legacy reason request still will be sent despite this error, but if before it had been left unhandled until llm finishes its response, not it'll be closed shortly after the error appears. 

Maybe someday I'll make it right, to halt stuff before request has been sent already.
